#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

# Install basic casks
# https://hackernoon.com/personal-macos-workspace-setup-adf61869cd79
declare -a taps=(
  'buo/cask-upgrade'
  'homebrew/cask-versions'
  'homebrew/bundle'
  'homebrew/core'
)

for tap in "${taps[@]}"; do
  brew tap "$tap"
done

brew upgrade && brew update && brew install cask

# Install cask apps
declare -a cask_apps=(
  'google-chrome'
  'iterm2'
  'postman'
  'spotify'
  'azure-cli'
  'google-cloud-skd'
  'awscli'
  'dropbox'
  'teamviewer'
  'powershell'
  'calibre'
  'github'
  'kubecontext'
  'signal'
  'vagrant'
  'discord'
  'skype'
  'docker'
  'gpg-suite-no-mail'
  'visual-studio-code'
  'synology-drive'
)

for app in "${cask_apps[@]}"; do
  brew cask install "$app"
done

# Install stuff from mac app store
brew install mas

declare -a mas_apps=(
  '824171161'   # Affinity Designer
  '918858936'   # Airmail 3
  '1091189122'  # Bear
  '736584830'   # Folx GO
  '775737590'   # iA Writer
  '441258766'   # Magnet
  '1063631769'  # Medis
  '967805235'   # Paste
  '583827028'   # WinZip
)

for app in "${mas_apps[@]}"; do
  mas install "$app"
done



cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
